### ISSUE TITLE
the test problem

### ISSUE THREAD

**Issue by yemeijuan** [hardmaru/sketch-rnn#5]
I saw your code on githubs,and trained with the aaron_sheep dataset.Then I got some files like "vector-500.meta", but I don't know how to test.Forgive my dull, and I hope you can tell me how to test.
      I got the training data,and I found "kL" has still been larger than 0.2 in the end, and "recon" become a negative.Is there a problem ? How should it be resolved?

**Comment by hardmaru** [comment]
try:

https://github.com/tensorflow/magenta/tree/master/magenta/models/sketch_rnn
